;pytest配置文件
[pytest]
;全局默认参数
addopts = -vs --alluredir=./reports --clean-alluredir
;测试脚本存放目录
testpaths = ./tests
; 测试文件命名规则
python_files = test_*.py
; 测试类命名规则
python_classes = Test*
; 测试函数命名规则
python_functions = test_*
; 注册自定义标记
markers =
    smoke: 冒烟用例（核心流程）
    normal: 普通用例
    exception: 异常场景用例